#!/usr/bin/env python
import argparse
import json
import os

def format_json(f):
    data = json.load(f)
    return json.dumps(data, indent=4)

def format(f):
    return f.read()

def main():

    parser = argparse.ArgumentParser(description='Pretty Print')
    parser.add_argument('file', type=str, help="Filename to pretty print")
    args = parser.parse_args()

    formatters = {
        ".json": format_json,
        }

    with open(args.file) as f:
        filename, ext = os.path.splitext(args.file)
        try:
            print formatters[ext](f)
        except KeyError:
            print format(f)
    

if __name__ == "__main__":
    main()


